meta_product_name: "Product Name"
meta_title: "finport - Integrate all your investments across brokers and banks in one place. Get started now for free."
meta_description: "Finport is a user-friendly, easy to use platform, which provides retail investors with a transparent overview of their various investments across brokers and banks"
meta_image: "finport_homepage_picture1.jpg" # should exist in `app/assets/images/`
